# Generated by Django 4.1.6 on 2023-02-06 12:15

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief_Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('work_experience', models.IntegerField(verbose_name='Стаж работы')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Главный врач',
                'verbose_name_plural': 'Главные врачи',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Медсестра',
                'verbose_name_plural': 'Медсестры',
            },
        ),
        migrations.CreateModel(
            name='Okpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpo', models.IntegerField(db_index=True, unique=True, verbose_name='ОКПО')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('diagnosis', models.TextField(verbose_name='Причина обращения в больницу')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chief_physician', verbose_name='Жалоба')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='okpo',
        ),
        migrations.RemoveField(
            model_name='nurses',
            name='okpo',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='okpo',
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Больница', 'verbose_name_plural': 'Больницы'},
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='status',
        ),
        migrations.AddField(
            model_name='hospital',
            name='public_private',
            field=main.models.CustomBooleanField(default=True, verbose_name='Государственная'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='employees',
            field=models.CharField(max_length=100, verbose_name='Сотрудники'),
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('direction', models.DateTimeField(max_length=200, verbose_name='Направление')),
                ('therapist_surgeon', models.BooleanField(default=True, verbose_name='Терапевт')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('pin_passport', models.CharField(max_length=14, verbose_name='ПИН-КОД паспорта')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('work_experience', models.IntegerField(verbose_name='Стаж работы')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.nurse', verbose_name='Медсестра')),
            ],
            options={
                'verbose_name': 'Лечащий врач',
                'verbose_name_plural': 'Лечащие врачи',
            },
        ),
        migrations.DeleteModel(
            name='Chiefphysician',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Nurses',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='patients',
            name='okpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='okpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='patients',
            field=models.ManyToManyField(to='main.patients', verbose_name='Пациенты'),
        ),
        migrations.AddField(
            model_name='chief_physician',
            name='okpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='okpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.okpo', unique=True, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='okpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital', verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='patients',
            field=models.ManyToManyField(to='main.patients', verbose_name='Пациенты'),
        ),
        migrations.AddField(
            model_name='chief_physician',
            name='therapist',
            field=models.ManyToManyField(to='main.therapist', verbose_name='Лечащий врач'),
        ),
    ]
